import type {
  AllowedAction,
  ItemLookupRecord,
  ItemRevisionLookupRecord,
  MaterialRequestRecord,
  MaterialRequestRow,
  WorkOrderLookups,
  WorkOrderRecord,
  WorkOrderRow,
} from '../types/workOrder'
import { formatDate, formatDateTime } from '../../../shared/lib/formatDate.ts'

const UNAVAILABLE = '-'

/** Never infer mutation availability from status — server allowed_actions is authoritative. */
export function findAllowedAction(
  actions: AllowedAction[] | undefined,
  action: string,
): AllowedAction | null {
  return actions?.find((item) => item.action === action) ?? null
}

export function isActionEnabled(actions: AllowedAction[] | undefined, action: string): boolean {
  return findAllowedAction(actions, action)?.enabled === true
}

/** Builds id->code lookup maps so raw FK ids are never rendered on the Work Order screen. */
export function buildWorkOrderLookups(input: {
  items: ItemLookupRecord[]
  revisions: ItemRevisionLookupRecord[]
}): WorkOrderLookups {
  const itemById = new Map<number, ItemLookupRecord>()
  for (const item of input.items) itemById.set(item.id, item)

  const revisionById = new Map<number, ItemRevisionLookupRecord>()
  for (const rev of input.revisions) revisionById.set(rev.id, rev)

  return { itemById, revisionById }
}

export function projectWorkOrderRow(wo: WorkOrderRecord, lookups: WorkOrderLookups): WorkOrderRow {
  const updateAction = findAllowedAction(wo.allowed_actions, 'update')
  const planAction = findAllowedAction(wo.allowed_actions, 'plan')
  const releaseAction = findAllowedAction(wo.allowed_actions, 'release')
  const pauseAction = findAllowedAction(wo.allowed_actions, 'pause')
  const resumeAction = findAllowedAction(wo.allowed_actions, 'resume')
  const closeAction = findAllowedAction(wo.allowed_actions, 'close')
  const cancelAction = findAllowedAction(wo.allowed_actions, 'cancel')

  const itemLabel = wo.item_code || lookups.itemById.get(wo.item_id)?.code || UNAVAILABLE
  const itemRevisionLabel =
    wo.item_revision_code ||
    (wo.item_revision_id != null ? lookups.revisionById.get(wo.item_revision_id)?.code : null) ||
    UNAVAILABLE

  return {
    id: wo.id,
    code: wo.code || UNAVAILABLE,
    itemLabel,
    itemRevisionLabel,
    bomLabel: wo.bom_code || UNAVAILABLE,
    routingLabel: wo.routing_code || UNAVAILABLE,
    status: wo.status || UNAVAILABLE,
    plannedQty: wo.planned_qty,
    producedQty: wo.produced_qty,
    scrapQty: wo.scrap_qty,
    plannedStart: wo.planned_start ? formatDate(wo.planned_start) : UNAVAILABLE,
    actualStart: wo.actual_start ? formatDateTime(wo.actual_start) : UNAVAILABLE,
    actualEnd: wo.actual_end ? formatDateTime(wo.actual_end) : UNAVAILABLE,
    releasedAt: wo.released_at ? formatDateTime(wo.released_at) : UNAVAILABLE,
    materialReadyAt: wo.material_ready_at ? formatDateTime(wo.material_ready_at) : UNAVAILABLE,
    canUpdate: updateAction?.enabled === true,
    canPlan: planAction?.enabled === true,
    canRelease: releaseAction?.enabled === true,
    canPause: pauseAction?.enabled === true,
    canResume: resumeAction?.enabled === true,
    canClose: closeAction?.enabled === true,
    canCancel: cancelAction?.enabled === true,
    updateAction,
    planAction,
    releaseAction,
    pauseAction,
    resumeAction,
    closeAction,
    cancelAction,
    updateDisabledReason: updateAction?.enabled ? null : updateAction?.disabled_reason_code ?? null,
    planDisabledReason: planAction?.enabled ? null : planAction?.disabled_reason_code ?? null,
    releaseDisabledReason: releaseAction?.enabled ? null : releaseAction?.disabled_reason_code ?? null,
    pauseDisabledReason: pauseAction?.enabled ? null : pauseAction?.disabled_reason_code ?? null,
    resumeDisabledReason: resumeAction?.enabled ? null : resumeAction?.disabled_reason_code ?? null,
    closeDisabledReason: closeAction?.enabled ? null : closeAction?.disabled_reason_code ?? null,
    cancelDisabledReason: cancelAction?.enabled ? null : cancelAction?.disabled_reason_code ?? null,
  }
}

/** Material requests are read-only on this screen (generated by release BOM explosion). */
export function projectMaterialRequestRow(mr: MaterialRequestRecord): MaterialRequestRow {
  return {
    code: mr.code || UNAVAILABLE,
    itemLabel: mr.item_code || UNAVAILABLE,
    requiredQty: mr.required_qty,
    uomLabel: mr.uom_code || UNAVAILABLE,
    targetLocationLabel: mr.target_location_code || UNAVAILABLE,
    status: mr.status || UNAVAILABLE,
  }
}

export function resolveWorkOrderListState(input: {
  status: 'loading' | 'success' | 'error'
  itemCount: number
  hasQuery: boolean
  errorCode: string | null
}): 'loading' | 'empty' | 'no-result' | 'permission-denied' | 'error' | 'ready' {
  if (input.status === 'loading') return 'loading'
  if (input.status === 'error') {
    return input.errorCode === 'PERMISSION_DENIED' ? 'permission-denied' : 'error'
  }
  if (input.itemCount === 0) return input.hasQuery ? 'no-result' : 'empty'
  return 'ready'
}

export function resolveMutationUiState(input: {
  confirmOpen: boolean
  status: 'idle' | 'pending' | 'success' | 'error'
  errorCode: string | null
}): 'idle' | 'confirm' | 'pending' | 'success' | 'permission-denied' | 'not-allowed' | 'error' {
  if (input.status === 'pending') return 'pending'
  if (input.status === 'success') return 'success'
  if (input.status === 'error') {
    if (input.errorCode === 'PERMISSION_DENIED') return 'permission-denied'
    if (input.errorCode === 'NOT_ALLOWED_BY_STATUS') return 'not-allowed'
    return 'error'
  }
  return input.confirmOpen ? 'confirm' : 'idle'
}

export function validateWorkOrderCreateForm(input: {
  code: string
  itemId: number
  plannedQty: number
  plannedStart: string
}): string[] {
  const errors: string[] = []
  if (!input.code.trim()) errors.push('code')
  if (!Number.isInteger(input.itemId) || input.itemId <= 0) errors.push('item_id')
  if (!Number.isInteger(input.plannedQty) || input.plannedQty <= 0) errors.push('planned_qty')
  if (!input.plannedStart.trim()) errors.push('planned_start')
  return errors
}

export function validateReasonForm(input: { reason: string }): string[] {
  const errors: string[] = []
  if (!input.reason.trim()) errors.push('reason')
  return errors
}
